### ISSUE TITLE
[Bug] Got an error while starting the server

### ISSUE THREAD

**Issue by Eatham532** [axieum/minecord#40]
### Expected behavior

irk

The server does not crash. I just get this error.

### Observed/actual behavior

Got the error:

```shell
[16:44:23] [Minecord-Presence-Timer/ERROR]: Uncaught exception in thread "Minecord-Presence-Timer"
java.lang.NoClassDefFoundError: me/axieum/mcmod/minecord/shadow/api/org/apache/commons/lang3/time/DurationFormatUtils
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at me.axieum.mcmod.minecord.api.util.StringTemplate.format(StringTemplate.java:269) ~[minecord-api-1.0.0-beta.2-334e7ed5a4687c1b.jar:?]
at me.axieum.mcmod.minecord.impl.presence.config.PresenceConfig$CategorySchema$PresenceSchema$1.getActivity(PresenceConfig.java:142) ~[minecord-presence-1.0.0-beta.2-b3c770a51ebc8da7.jar:?]
at me.axieum.mcmod.minecord.impl.presence.PresenceUpdateTask.run(PresenceUpdateTask.java:96) ~[minecord-presence-1.0.0-beta.2-b3c770a51ebc8da7.jar:?]
at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
at java.util.TimerThread.run(Timer.java:516) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.axieum.mcmod.minecord.shadow.api.org.apache.commons.lang3.time.DurationFormatUtils
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 5 more
```

### Steps/models to reproduce

Add the mod to your server.

Look at the logs.

### Version

1.0.0 beta 2

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment]
Hi @Eatham532, there are a few things I need to fix with the publishing of these shadow jars. In the meantime, you can download the mod jars from here: https://github.com/axieum/minecord/suites/7179538609/artifacts/286386638

**Comment by Eatham532** [comment]
Thank you!
