### ISSUE TITLE
Exception while stopping the server 

### ISSUE THREAD

**Issue by Eatham532** [axieum/minecord#44]
### Expected behavior

The server to stop

### Observed/actual behavior

Get this error

```shell
[12:15:00] [Server thread/ERROR]: Exception stopping the server
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.minutes-UwyO8pc(long)'
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at com.github.quiltservertools.ledger.Ledger$serverStopped$1.invokeSuspend(Ledger.kt:100) ~[ledger-1.2.5.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[minecord-api-1.0.0-beta.2-37094233aadedb4d.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
at com.github.quiltservertools.ledger.Ledger.serverStopped(Ledger.kt:99) ~[ledger-1.2.5.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$6(ServerLifecycleEvents.java:76) ~[fabric-lifecycle-events-v1-2.1.0+33fbc738a9-c697e79f4c4115d8.jar:?]
at net.minecraft.server.MinecraftServer.handler$cji000$afterShutdownServer(MinecraftServer:8306) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer:610) ~[server-intermediary.jar:?]
at net.minecraft.server.dedicated.MinecraftDedicatedServer.shutdown(MinecraftDedicatedServer:547) ~[?:?]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps/models to reproduce

Stop the server

### Version

1.0.0 beta 2 (The one you gave me)

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment]
Hmm, this might be an incompatibility issue with Quilt. I'll need to reproduce this with your list of server mods.

**Comment by Eatham532** [comment]
Ok, I am not using quilt. Here is a screenshot of all my server mods. Fyi, ccme and vmp was added after the crash. 

![image](https://user-images.githubusercontent.com/78714349/177226802-f341e9de-314f-41c4-a8c9-46e7ae067cb7.png)

**Comment by axieum** [comment]
This appears to be an issue with the [QuiltServerTools/Ledger](https://github.com/QuiltServerTools/Ledger) project:

```
[12:15:00] [Server thread/ERROR]: Exception stopping the server
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.minutes-UwyO8pc(long)'
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at com.github.quiltservertools.ledger.Ledger$serverStopped$1.invokeSuspend(Ledger.kt:100) ~[ledger-1.2.5.jar:?]
```

https://github.com/QuiltServerTools/Ledger/blob/eefeb20dd4d9b8fe9fe9953698339e0e2a3e72e2/src/main/kotlin/com/github/quiltservertools/ledger/Ledger.kt#L100

Minecord does not use Kotlin, while the Ledger project is written in Kotlin.

If Minecord is indeed affecting other mods that use Kotlin, it might be a dependency (like JDA) that is adding a different version of Kotlin to the classpath. But given Ledger is using 'experimental' time, as denoted by `@OptIn(ExperimentalTime::class)`, I'd rather wait to see if it's an issue on Ledger's side before I denote too much time to this issue.

**Comment by Eatham532** [comment]
Ok, Sure.
